/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import javax.swing.*;
import civitas.*;

/**
 *
 * @author pedrobedmar
 */
public class CivitasView extends javax.swing.JFrame {
    
    /**
     * Creates new form CivitasView
     */
    
    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    CasillaActualPanel casillaActualPanel;
    GestionarDialog gestionarD;
    
    public CivitasView(){
        initComponents();
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add(jugadorPanel);
        casillaActualPanel = new CasillaActualPanel();
        contenedorVistaCasillaActual.add(casillaActualPanel);
        gestionarD = new GestionarDialog(this,true);
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
    void setCivitasJuego(CivitasJuego juego){
        this.juego=juego;
        setVisible(true);

    }
    
    int getPropiedad(){
        return gestionarD.getPropiedad();
    }
    
    int getGestion(){
        return gestionarD.getGestion();
    }
     
    void actualizarVista(){
        jugadorPanel.setJugador(juego.getJugadorActual());
        casillaActualPanel.setCasillaActual(juego.getCasillaActual());
        labelFinDelJuego.setVisible(false);
        textAreaFinDelJuego.setVisible(false);
        if(juego.finalDelJuego()){
           String texto = "";
           for (Jugador j: juego.ranking()){
               texto+=j.toString();
               texto+="\n";
           }
           textAreaFinDelJuego.setText(texto);
           labelFinDelJuego.setVisible(true);
           textAreaFinDelJuego.setVisible(true);
           repaint();
           revalidate();
        }
        repaint();
        revalidate();
    }

    void mostrarSiguienteOperacion(OperacionesJuego operacion){
        textSiguienteOperacion.setText(operacion.toString());
        actualizarVista();
    }
    
    void mostrarEventos(){
        DiarioDialog diarioD=new DiarioDialog(this);
    }
    
    Respuestas comprar(){
        int opcion= JOptionPane.showConfirmDialog(null,"¿Quieres comprar la calle actual?","Compra", JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            return Respuestas.SI;
        } else {
            return Respuestas.NO;
        }
    }
    
    void gestionar(){
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
    }
    
    SalidasCarcel salirCarcel(){
        String[] opciones ={"Pagando", "Tirando"};
        int respuesta= JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?", "Salir de la cárcel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0] );
        if(respuesta==0){
            return SalidasCarcel.PAGANDO;
        } else {
            return SalidasCarcel.TIRANDO;
        }
    }
     
             
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        contenedorVistaCasillaActual = new javax.swing.JPanel();
        labelSiguienteOperacion = new javax.swing.JLabel();
        textSiguienteOperacion = new javax.swing.JTextField();
        labelFinDelJuego = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaFinDelJuego = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Amigos", 0, 24)); // NOI18N
        jLabel1.setText("Civitas, The Game");

        labelSiguienteOperacion.setText("Siguiente Operación:");

        textSiguienteOperacion.setText("jTextField1");
        textSiguienteOperacion.setEnabled(false);
        textSiguienteOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSiguienteOperacionActionPerformed(evt);
            }
        });

        labelFinDelJuego.setText("Fin del Juego:");

        textAreaFinDelJuego.setColumns(18);
        textAreaFinDelJuego.setRows(5);
        textAreaFinDelJuego.setEnabled(false);
        jScrollPane1.setViewportView(textAreaFinDelJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFinDelJuego)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSiguienteOperacion)
                                .addGap(40, 40, 40)
                                .addComponent(textSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(contenedorVistaCasillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contenedorVistaCasillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSiguienteOperacion)
                            .addComponent(textSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(labelFinDelJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSiguienteOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSiguienteOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSiguienteOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorVistaCasillaActual;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFinDelJuego;
    private javax.swing.JLabel labelSiguienteOperacion;
    private javax.swing.JTextArea textAreaFinDelJuego;
    private javax.swing.JTextField textSiguienteOperacion;
    // End of variables declaration//GEN-END:variables
}
