/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.util.ArrayList;
import civitas.*;

/**
 *
 * @author pedrobedmar
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    Jugador jugador;
    
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void setJugador(Jugador jugador){
        this.jugador=jugador;
        textNombre.setText(jugador.getNombre());
        textSaldo.setText(Float.toString(jugador.getSaldo()));
        textEncarcelado.setText(Boolean.toString(jugador.isEncarcelado()));
        if(jugador.getClass().getName()=="civitas.JugadorEspeculador"){
            textEspeculador.setText(Boolean.toString(true));
        } else {
            textEspeculador.setText(Boolean.toString(false));
        }
        repaint();
        rellenaPropiedades(jugador.getPropiedades());       //Esto va antes o después del revalidate?
    }
    
    private void rellenaPropiedades(ArrayList<TituloPropiedad> lista){
        propiedades.removeAll();
        for(TituloPropiedad t:lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        repaint();
        revalidate();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        labelEncarcelado = new javax.swing.JLabel();
        labelEspeculador = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textSaldo = new javax.swing.JTextField();
        textEncarcelado = new javax.swing.JTextField();
        textEspeculador = new javax.swing.JTextField();
        propiedades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelNombre.setText("Nombre:");

        labelSaldo.setText("Saldo:");

        labelEncarcelado.setText("¿Encarcelado?");

        labelEspeculador.setText("¿Especulador?");

        textNombre.setText("jTextField1");
        textNombre.setEnabled(false);

        textSaldo.setText("jTextField1");
        textSaldo.setEnabled(false);

        textEncarcelado.setText("jTextField1");
        textEncarcelado.setEnabled(false);

        textEspeculador.setText("jTextField1");
        textEspeculador.setEnabled(false);
        textEspeculador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEspeculadorActionPerformed(evt);
            }
        });

        propiedades.setBackground(new java.awt.Color(153, 204, 255));
        propiedades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Propiedades");
        propiedades.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Jugador Actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelSaldo)
                            .addComponent(labelEncarcelado)
                            .addComponent(labelEspeculador))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldo)
                    .addComponent(textSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEncarcelado)
                    .addComponent(textEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEspeculador)
                    .addComponent(textEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textEspeculadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEspeculadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEspeculadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelEncarcelado;
    private javax.swing.JLabel labelEspeculador;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JPanel propiedades;
    private javax.swing.JTextField textEncarcelado;
    private javax.swing.JTextField textEspeculador;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textSaldo;
    // End of variables declaration//GEN-END:variables
}
